/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardQueueRouteImport } from './routes/dashboard.queue'
import { Route as DashboardLibraryRouteImport } from './routes/dashboard.library'
import { Route as DashboardExtensionRouteImport } from './routes/dashboard.extension'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as ApiWorkerReportRouteImport } from './routes/api/worker.report'
import { Route as ApiQueuePauseRouteImport } from './routes/api/queue.pause'
import { Route as ApiQueueAddRouteImport } from './routes/api/queue.add'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQueueRoute = DashboardQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLibraryRoute = DashboardLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExtensionRoute = DashboardExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiWorkerReportRoute = ApiWorkerReportRouteImport.update({
  id: '/api/worker/report',
  path: '/api/worker/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueuePauseRoute = ApiQueuePauseRouteImport.update({
  id: '/api/queue/pause',
  path: '/api/queue/pause',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueueAddRoute = ApiQueueAddRouteImport.update({
  id: '/api/queue/add',
  path: '/api/queue/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/extension': typeof ExtensionRoute
  '/pricing': typeof PricingRoute
  '/workspace': typeof WorkspaceRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/extension': typeof DashboardExtensionRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/queue': typeof DashboardQueueRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/queue/add': typeof ApiQueueAddRoute
  '/api/queue/pause': typeof ApiQueuePauseRoute
  '/api/worker/report': typeof ApiWorkerReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/extension': typeof ExtensionRoute
  '/pricing': typeof PricingRoute
  '/workspace': typeof WorkspaceRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/extension': typeof DashboardExtensionRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/queue': typeof DashboardQueueRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/queue/add': typeof ApiQueueAddRoute
  '/api/queue/pause': typeof ApiQueuePauseRoute
  '/api/worker/report': typeof ApiWorkerReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/extension': typeof ExtensionRoute
  '/pricing': typeof PricingRoute
  '/workspace': typeof WorkspaceRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/extension': typeof DashboardExtensionRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/queue': typeof DashboardQueueRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/queue/add': typeof ApiQueueAddRoute
  '/api/queue/pause': typeof ApiQueuePauseRoute
  '/api/worker/report': typeof ApiWorkerReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/extension'
    | '/pricing'
    | '/workspace'
    | '/dashboard/admin'
    | '/dashboard/billing'
    | '/dashboard/extension'
    | '/dashboard/library'
    | '/dashboard/queue'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/queue/add'
    | '/api/queue/pause'
    | '/api/worker/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/extension'
    | '/pricing'
    | '/workspace'
    | '/dashboard/admin'
    | '/dashboard/billing'
    | '/dashboard/extension'
    | '/dashboard/library'
    | '/dashboard/queue'
    | '/dashboard/settings'
    | '/dashboard'
    | '/api/queue/add'
    | '/api/queue/pause'
    | '/api/worker/report'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/extension'
    | '/pricing'
    | '/workspace'
    | '/dashboard/admin'
    | '/dashboard/billing'
    | '/dashboard/extension'
    | '/dashboard/library'
    | '/dashboard/queue'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/queue/add'
    | '/api/queue/pause'
    | '/api/worker/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ExtensionRoute: typeof ExtensionRoute
  PricingRoute: typeof PricingRoute
  WorkspaceRoute: typeof WorkspaceRoute
  ApiQueueAddRoute: typeof ApiQueueAddRoute
  ApiQueuePauseRoute: typeof ApiQueuePauseRoute
  ApiWorkerReportRoute: typeof ApiWorkerReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/queue': {
      id: '/dashboard/queue'
      path: '/queue'
      fullPath: '/dashboard/queue'
      preLoaderRoute: typeof DashboardQueueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/library': {
      id: '/dashboard/library'
      path: '/library'
      fullPath: '/dashboard/library'
      preLoaderRoute: typeof DashboardLibraryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/extension': {
      id: '/dashboard/extension'
      path: '/extension'
      fullPath: '/dashboard/extension'
      preLoaderRoute: typeof DashboardExtensionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/worker/report': {
      id: '/api/worker/report'
      path: '/api/worker/report'
      fullPath: '/api/worker/report'
      preLoaderRoute: typeof ApiWorkerReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/queue/pause': {
      id: '/api/queue/pause'
      path: '/api/queue/pause'
      fullPath: '/api/queue/pause'
      preLoaderRoute: typeof ApiQueuePauseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/queue/add': {
      id: '/api/queue/add'
      path: '/api/queue/add'
      fullPath: '/api/queue/add'
      preLoaderRoute: typeof ApiQueueAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardExtensionRoute: typeof DashboardExtensionRoute
  DashboardLibraryRoute: typeof DashboardLibraryRoute
  DashboardQueueRoute: typeof DashboardQueueRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardExtensionRoute: DashboardExtensionRoute,
  DashboardLibraryRoute: DashboardLibraryRoute,
  DashboardQueueRoute: DashboardQueueRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ExtensionRoute: ExtensionRoute,
  PricingRoute: PricingRoute,
  WorkspaceRoute: WorkspaceRoute,
  ApiQueueAddRoute: ApiQueueAddRoute,
  ApiQueuePauseRoute: ApiQueuePauseRoute,
  ApiWorkerReportRoute: ApiWorkerReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
